name: CI
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src build.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        step: [install, test]
        release: [release=true, release=false]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build ${{ matrix.step }} -D${{ matrix.release }}
