name: CI
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check src build.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        step: [install, test]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - if: matrix.os == 'ubuntu-latest' && matrix.step == 'install'
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev -y

      - name: zig build ${{ matrix.step }} -Doptimize=${{ matrix.optimize }}
        run: zig build ${{ matrix.step }} -Doptimize=${{ matrix.optimize }}
