name: CI
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.7.1
      - run: zig build build-cli
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.7.1
      - run: zig fmt --check .
