name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.8.0
      - run: zig build test
      - run: zig build test -Drelease
      - run: zig build -Dbuild-ui=false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.8.0
      - run: zig fmt --check .
