name: CI
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        step: [install, test]
        release: [-Drelease=true, -Drelease=false]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig build ${{matrix.step}} ${{matrix.release}}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig fmt --check src build.zig
