name: CI
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1.2.5
        with:
          version: 0.7.0
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install xorg libxft-dev
        run: zig build
      - if: matrix.os != 'ubuntu-latest'
        run: zig build
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: goto-bus-stop/setup-zig@v1.2.5
        with:
          version: 0.7.0
      - run: zig fmt --check .
