name: Release
on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src build.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        release: [release=true, release=false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build test -D${{ matrix.release }}

  build:
    strategy:
      matrix:
        target: [x86_64-linux-gnu, x86_64-windows-gnu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: |
          zig build -Dstrip -Drelease -Dtarget=${{ matrix.target }}
          ./make-zip.sh metronome-${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: metronome-${{ matrix.target }}
          path: metronome-${{ matrix.target }}.zip
          retention-days: 1

  create-release:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Creating release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls /usr/lib/ || true
          gh release delete nightly --yes || true
          git push origin :nightly || true
          gh release create nightly --prerelease --title "Nightly" --notes " " **/*.zip
